menu:
  Home: /
  Blog: /list/
  About: /about/
  CV: /cv/
  # ...

showInMenu:  # menu 中的哪些页面显示在首页中（“首页”必定显示）
  - Blog
  - About
  - CV
  # - 标签
  # - 分类


index:  # 首页的页眉页脚
  header: Societas Eruditorum. ignoti et quasi occulti
  footer: Email:pashtet04@gmail.com
  titlePosition: left # center | left  # 首页标题的位置

footerLink: # 底部的链接自定义
  tags: /tags/
  categories: /categories/
  info:  # info这个单词不能修改，不想使用可为空
  # 添加链接格式 举例
  # 友链: /friends/ # 需要hexo new page friends
  contact: /contact/ # 需要hexo new page contact
  # 支持: /support/ # 需要hexo new page support
  # ...

post: #除首页之外页面
  footer: 🌊Societas Eruditorum. ignoti et quasi occulti🌊   # 底部左侧 自定义信息
  themeInfo: true # true | false  # 是否开启 底部右侧 声明本站信息

# 相对于source目录下的头像url
favicon: img/favicon.ico

# ---------------------------------------------------------------------------------------
# 以上为基本配置，实现了A4主题追求的纯净风
# 
# 以下为 非必要不必更改的配置
#
# ps：还有经过A4作者测试，可供你使用的插件，详见：https://ninojay.top/tags/hexoPlugin/
# ---------------------------------------------------------------------------------------

# 你可能会用到的 https://ninojay.top/2023/website-cdn/
cdn:
  enable: false # 如果你修改了 css/js ，也许需要把cdn设置为false才会生效
  choose: jsdelivr  # aliyun | unpkg| jsdelivr  # 都调整为利于国内的cdn，建议使用默认的 jsdelivr 即可

# 实验性功能：A4色调调整：颜色搭配是很主观的行为
# 设置为 false 为 A4 默认灰白色调，可设置为 true 直接启动 体验下 另一种绿金预置色调
# 注：颜色代码需加“#”，颜色单词不需要加“#”
# 更多A4色调搭配推荐：https://ninojay.top/hexoplugin/A4-color-change/
color: 
  enable: false # true | false 
  font: "#fec591" # 字体颜色
  background: "#005454" # 最底部层背景颜色
  indexBackGround: "#005454" # 首页层颜色
  postBackGround: "#005454" # 文章页层颜色
  codeBackGround: "black" # 代码块背景颜色
  codeFont: "white" # 代码块字体颜色 
  linkBeforeClick: "#fec591" # 链接点击前的颜色
  linkAfterClick: "#fec591" # 链接点击后的颜色

# ---------------------------------------------------------------------------------------
# Comment plugin
# 评论插件：需要根据教程自行部署评论服务
# ---------------------------------------------------------------------------------------
comment:
  enable: true 
  use: waline # values: waline

  # Waline
  # See: https://waline.js.org/guide/get-started.html
  waline:
    serverUrl: https://kubertyops-waline.vercel.app/ # Waline server url(vercel) example: https://example.example.com
    lang: ru-RU # Waline language, default: zh-CN. See: https://waline.js.org/guide/client/i18n.html


version: v1.7.0
